table 'Returns Data'
	lineageTag: 87ebd6f3-a2f1-4ca1-93f6-7d1ec8712434

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a00d333b-8f0a-4ab4-b7e0-cac2b5e9ef6b
		summarizeBy: none
		sourceColumn: ReturnDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 99032a87-5413-4f94-99b6-36cec1d2e8a1
		summarizeBy: none
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: a56e39ce-1c80-43fb-b57e-05bb4de59e27
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: f226e2e0-2d13-48af-83ee-d926467fc5bd
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Returns Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\prath\Desktop\Adventure Works-Latest\Adventure Works-Latest\AdventureWorks Returns Data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnDate", type date}, {"TerritoryKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

